import type {Metadata} from "next";
import Menu from "@/components/menu/menu";
import UserPage from "@/app/(privat)/users/[id]/page";

export const metadata: Metadata = {
    title: "UsersLayout",
    description: "Generated by create next app",
};

type Props = {
children?: React.ReactNode;
}

const UsersLayout = ({
    children}: Props) => {
    return (
        <>

            {children}
        </>
    );
}
export default UsersLayout;
